"""Add Stripe payout and order reservation fields

Revision ID: b6e70cf5c205
Revises: 0678de994d5e
Create Date: 2026-07-22 08:56:37.651452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e70cf5c205'
down_revision = '0678de994d5e'
branch_labels = None
depends_on = None


def upgrade():
    inspector = sa.inspect(op.get_bind())
    order_columns = {column['name'] for column in inspector.get_columns('order')}
    user_columns = {column['name'] for column in inspector.get_columns('user')}

    if 'expires_at' not in order_columns:
        with op.batch_alter_table('order', schema=None) as batch_op:
            batch_op.add_column(sa.Column(
                'expires_at', sa.DateTime(timezone=True), nullable=False,
                server_default=sa.text('CURRENT_TIMESTAMP'),
            ))

    with op.batch_alter_table('user', schema=None) as batch_op:
        if 'stripe_charges_enabled' not in user_columns:
            batch_op.add_column(sa.Column(
                'stripe_charges_enabled', sa.Boolean(), nullable=False,
                server_default=sa.false(),
            ))
        if 'stripe_payouts_enabled' not in user_columns:
            batch_op.add_column(sa.Column(
                'stripe_payouts_enabled', sa.Boolean(), nullable=False,
                server_default=sa.false(),
            ))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('stripe_payouts_enabled')
        batch_op.drop_column('stripe_charges_enabled')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
