<script setup>
import { reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { api } from '../lib'
const router = useRouter(); const error = ref(''); const form = reactive({ title: '', description: '', venue: '', county: '', startsAt: '', category: 'Music', ticketPrice: '', ticketCapacity: '' })
async function submit() { error.value = ''; try { await api('/events', { method: 'POST', body: JSON.stringify({ ...form, ticketPriceCents: Math.round(Number(form.ticketPrice) * 100), ticketCapacity: Number(form.ticketCapacity) }) }); router.push('/organiser') } catch (err) { error.value = err.message } }
</script>
<template><section class="form-page shell"><div class="form-intro"><p class="eyebrow">Bring people together</p><h1>Host an event</h1><p>Tell us the essentials. Your listing stays private until EventSpace reviews and verifies it.</p><div class="review-note"><strong>No upfront listing fee</strong><span>We take 4% only when a ticket sells.</span></div></div><form class="form-card form-card--wide" @submit.prevent="submit"><p v-if="error" class="form-error">{{ error }}</p><label>Event title<input v-model="form.title" required /></label><label>Description<textarea v-model="form.description" rows="6" required></textarea></label><div class="field-row"><label>Venue<input v-model="form.venue" required /></label><label>County<input v-model="form.county" required /></label></div><div class="field-row"><label>Date and time<input v-model="form.startsAt" type="datetime-local" required /></label><label>Category<select v-model="form.category"><option>Music</option><option>Comedy</option><option>Sports</option><option>Festival</option><option>Food & Drink</option><option>Education</option></select></label></div><div class="field-row"><label>Ticket price (€)<input v-model="form.ticketPrice" type="number" min="0" step="0.01" required /></label><label>Number of tickets<input v-model="form.ticketCapacity" type="number" min="1" required /></label></div><button class="button" type="submit">Submit for verification</button></form></section></template>

